import localFont from "next/font/local";
import "./globals.css";
import Navbar from '/src/Components/Navbar/Navbar.jsx'
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Dua & Ruqyah | All Duas Collection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://i.ibb.co/fYXX6jJ/logo-1.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-4 bg-gray-300">
          <div><Navbar></Navbar></div>
          <div>
            {children}
          </div>
          <div>hee</div>
        </div>
      </body>
    </html>
  );
}
